# Dependencies
markdown:  redcarpet
pygments:  true

# Permalinks
permalink:  pretty
relative_permalinks:  true

# Setup
baseurl:  /
title:  RCDT
url:  http://eden.rutgers.edu/~dancetrp

author:  Rutgers Chinese Dance Troupe
