# Dependencies
markdown:  redcarpet
highlighter:  rouge

# Permalinks
permalink:  pretty

# Setup
baseurl:  /
title:  RCDT
url:  http://eden.rutgers.edu/~dancetrp

author:  Rutgers Chinese Dance Troupe
